[package]
name = "data-science-grundlagen"
version = "0.1.0"
edition = "2021"
default-run = "default"

[dependencies]
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "default"
path = "src/main.rs"

[[bin]]
name = "exercise-1"
path = "exercise-1/main.rs"
